angler: QCamera: remove unused private fields
device/huawei/angler/camera/QCamera2/HAL3/QCamera3Mem.h:123:10: error:
private field 'mQueueAll' is not used [-Werror,-Wunused-private-field]
    bool mQueueAll;
         ^

device/huawei/angler/camera/QCamera2/HAL/QCameraParameters.h:87:24:
error: private field 'mParent' is not used
[-Werror,-Wunused-private-field]
    QCameraParameters *mParent;
                       ^
device/huawei/angler/camera/QCamera2/HAL/QCameraParameters.h:90:10:
error: private field 'mScaleDirection' is not used
[-Werror,-Wunused-private-field]
    bool mScaleDirection;   // 0: Upscaling; 1: Downscaling

Change-Id: I4834c79effdc6d17b0ffbea1b68f5ac73f582dc9